### ISSUE TITLE
Does it support CMI5 ?

### ISSUE THREAD

**Issue by zabojad** [Brightcookie/lxHive#133]
Hi! I did not see this information in the project description. Does lxHive supports CMI5 or is there any plan to support it?

**Comment by RoboSparrow** [comment]
Hi, 

lxHive accepts cmi 5 driven statements as per xAPI specs: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-About.md#appendix-b-cmi5-examplestatements

tdlr; 
 * data storage: yes, 
 * data management: out of scope of an LRS

[CMI5](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md) is a specification for learning management systems (LMS).

lxHive is a learning record store (LRS). It's scope is just to store and serve (xAPI conformant) learning records. 

The core component of an cmi5 compliant LMS may be an xAPI LRS like lxHive or learninglocker.

CMI5 specs are finally stable since June 2016 and we are actively evaluating them and possible impacts on lxHive development. 

One discussion we have is whether we should integrate cmi5 logic into the LRS and if so, how much. We are tending to keep a clearly modularized approach. A core LRS handling cmi5 driven workflows will likely create conflicts with the LMS above it. 

Hope I could answer your question. 

@sraka1 & @leogaggl please chime in

**Comment by zabojad** [comment]
Hi @RoboSparrow ! Thank you for your detailed answer. Yes it makes sense indeed, maybe cmi5 module distribution should be a LMS task only...

I've developed cmi5 modules and tested them on scorm cloud and I've noticed that there are checks that have to be handled by the LRS in a CMI5 context. For example, scorm cloud forbids you to send any other xAPI statement before your CMI5 module sends an "initiated" one. I guess with lxHive, it's probably not the case though?

**Comment by RoboSparrow** [comment]
@zabojad 
 sorry for replying so late.

> For example, scorm cloud forbids you to send any other xAPI statement before your CMI5 module sends an "initiated" one. I guess with lxHive, it's probably not the case though?

lxHive **core** will not include this kind of intelligence as it might conflict with a wrapping LMS (or any 
 other system/client) which is in control of the business logic (be it CMI-5 or anything else)

However, with our upcoming new release, we started a modularization process. This includes the ability to create *extensions* (or plugins) to the LRS core. This plugin layer will be the right place to add cmi-5 validation (or any other business logic).
