### ISSUE TITLE
X-Experience-API-Version header missing (MS VB.Net)

### ISSUE THREAD

**Issue by leogaggl** [Brightcookie/lxHive#44]
I took the code out of my VR environment and put it on to a ASP web page....
and I get the same result

<%
Dim xmlhttp
on error resume next

  Set xmlhttp = Server.CreateObject("MSXML2.ServerXMLHTTP")
  xmlhttp.setTimeouts 30,500,1000,1000
  xmlhttp.Open "post", "http://360evolve.saas.lxhive.com/statement", false
  xmlhttp.setRequestHeader "Accept", "*/*"
  xmlhttp.setRequestHeader "Authorization", "Basic p9cTBJSnsq1meX4lLT5ltnchZ5MT2mR0HnY2Y3Iv:NUmljosTsnNcXMeWmTroJbceax9lw48eUNV61eFn"
  xmlhttp.setRequestHeader "X-Experience-API-Version", "1.0.1"
  xmlhttp.setRequestHeader "Content-Type", "application/json"
  
  if Err.Number Then response.write Err.Description &"..." : Err.clear

  xmlhttp.Send
  If Err.Number Then
  	response.write("Something went wrong at the xAPI End")
    Err.Clear
  Else
  	response.write(xmlhttp.ResponseText)
  End If
  
  On Error Goto 0
  set xmlhttp = nothing

%>

the error I keep getting is {"error_message":"X-Experience-API-Version header missing."}

From other forums I think your server is not recognizing the 1.0.1 as the About i responding with a null !

as the about show...null

**Comment by DunkenKBliths** [comment]
Thanks Leo...

**Comment by RoboSparrow** [comment]
We have a look into this. It looks like the LRS is not configured for `1.0.1`.
'The supported versions can be set in the [Config.yaml](https://github.com/Brightcookie/lxHive/blob/master/src/xAPI/Config/Config.template.yml) of the LRS
Defaults are
...
xAPI:
    latest_version: 1.0.3
    ...
    supported_versions: [1.0.3]
...

So this should work when we change ` supported_versions`  to `[1.0.3, 1.0.1]`.
However the error returned is certainly misleading. A revision of the error handling is part of milestone 0.9.2
Apart from this I am not sure about the "Accept" header being correctly set.

**Comment by RoboSparrow** [comment]
@sraka1 What puzzles me is that GET 360evolve.saas.lxhive.com/about endpoint returns `{"version":null}` body. this is not the response I expected ({"version":[1.0.3]})
Apart from this: we need to re-issue a new token to the client and invalidate the one mentioned in the issue.

**Comment by DunkenKBliths** [comment]
I have altered the above code to point to 
**xmlhttp.setRequestHeader "X-Experience-API-Version", "1.0.3"**

the error now is

**Send response error : The date in the certificate is invalid or has expired ...**

_Do I need to delete all my end points and start afresh ?_

Also the Admin Site has been down for a while with a **500 Server Error** (when I try logging in)

**Comment by RoboSparrow** [comment]
Hi @DunkenKBliths We have an issue with the SSL certificate for this endpoint. I have logged this internally with high urgency to our Sysadmins. Apologies for that.

**Comment by DunkenKBliths** [comment]
No worries mate...looking forward to getting this working...

**Comment by RoboSparrow** [comment]
@DunkenKBliths @sraka1 

> Do I need to delete all my end points and start afresh ?

No, we just issue a new token which you replace in your Authentication header. This is just a security measure.

**Comment by sraka1** [comment]
@DunkenKBliths 
Sorry this took a bit longer, I needed to install Mono as we don't use Microsoft technologies and that took some time.

There are a couple problems in here:
Firstly, [as described in this SO answer](http://stackoverflow.com/questions/161343/how-do-i-prevent-serverxmlhttp-from-automatically-following-redirects-http-303), _ServerXMLHTTP_ does not resend the headers that were set on the original request if it receives a redirect response. 
You were getting a 302 redirect response, because you were calling **http** instead of **https** (we only support **https** for security reasons). This caused the "X-Experience-API-Version" header missing error on the second request. If you change the URL scheme in your code to https, this error disappears. This is a problem with the component you're using, not the LRS (looks like _ServerXMLHTTP_ is not fully conformant to HTTP spec).

Secondly, the correct endpoint is /statement**s**, not /statement.

Thirdly, it looks like you're not encoding your Authorization header? There is a ":" char in there, which isn't valid per base64 (probably forgot to do a base64 on that string?).

As for the version on the about endpoint returning null, that should now be resolved and the fix has already been deployed on production.

Please re-open this issue if you encounter any other server issues, I will close it for now. Thanks!
