### ISSUE TITLE
Activity Profile API - returned objectType is always "Activity"

### ISSUE THREAD

**Issue by RoboSparrow** [Brightcookie/lxHive#9]
I think the activity `objectTypes `are returned incorrectly. They always appear as objectType "Activity", even if they are of one of the other allowed [Activity types](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#description-9)

Example:

Statement: `ee438260-59d9-489f-ad8a-59cedcf0f21c`
POSTS an object

```
{
    id: "e79cbe5e-be22-4ef9-b16d-0bd64f6a6fb8",
    objectType: "StatementRef"
}
```
GET http://dev.experience.at/activities?activityId=e79cbe5e-be22-4ef9-b16d-0bd64f6a6fb8
however returns

```
{"id":"e79cbe5e-be22-4ef9-b16d-0bd64f6a6fb8","objectType":"Activity"}
```

The xAPI states that an Object can be of these types:

* Activity,
* Agent, Group,
* SubStatement
* StatementRef

My understanding is that ONLY `Activites` are to be stored in the activity profile api.

There is however a booby-trap. The `objectType` param is optional for type `Activity`, so it can be omitted on POST but needs to be identified as `Acitivity`. The other types listed require the `objectType` param according to the specs.

So the LRS needs IMO first to validate for an Activity this way:

*  true, if Object has `objectType `param && `objectType .value === 'Activity'`
*  true, if  `objectType` param is NOT set, but Object has a param `id` with a valid IRI

[Notes]
* issue migrated from https://bitbucket.org/brightcookie/closed-xat-beta/issues/73
* xAPI section: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#414-object
* quick tests:  http://thedesignspace.net/misc/xapi/#top

**Comment by sraka1** [comment]
This should work, as the check is implemented in https://github.com/Brightcookie/lxHive/blob/development/src/xAPI/Document/Statement.php#L139

I've also tested it with an example similar to the one you provided (with a StatementRef) and it seems to be working.

If you look at the code a couple of lines below though, you see that extraction of contextActivities and such is commented out due to performance reasons (temporarily). I think we should revisit this - I'll do a quick benchmark and create a new issue.

Closing this one.
